#!/bin/bash

## Removendo travas eventuais no apt
sudo rm /var/lib/dpkg/lock-fontend && sudo rm /var/cache/apt/archives/lock

## Indo para home
cd $HOME

## Linguagens
sudo apt install julia

## Vim
sudo apt install vim 
Config=(
	"set number"
	"syntax on"
	"set tabstop=2"
	"set autoindent"
)
touch ~/.vimrc
for config in ${Config[*]}; do
	echo $config >> ~/.vimrc
done
VIM_TEMPLATE="/DebianPosInstall/.vim"
if [ ! -d fightcade ]; then
	mv VIM_TEMPLATE $HOME
fi

## Movendo pastas do repo
mkdir Programas
fightcade="/DebianPosInstall/figthcade "
if [ ! -d fightcade ]; then
	mv fightcade Programas
fi

## Criando Lista de Favoritos do Chrome
FAV=(
	"LEARN 													- https://www.youtube.com/playlist?list=PLGNztVHyC5OpR_ZOAvUcN4kROML6sVPbd"
	"SergioAlmeidaCiprianoJr 								- https://github.com/SergioAlmeidaCiprianoJr"
	"SergioAlmeidaCiprianoJr 								- https://gitlab.com/SergioAlmeidaCiprianoJr"
	"CD-MOJ 												- https://moj.naquadah.com.br/cgi-bin/index.sh"
	"Telegram												- https://web.telegram.org"
	"Wpp Web												- https://web.whatsapp.com/"
	"Matricula Web 											- https://matriculaweb.unb.br/graduacao/sec/login.aspx"
	"Apender UnB											- https://aprender.ead.unb.br/"
	"MIT open course ware									- https://ocw.mit.edu/index.htm"
	"IRC													- https://irc.lappis.rocks/"
	"Livro de Shell											- https://bash.cyberciti.biz/guide/Main_Page"
	"URI 													- https://www.urionlinejudge.com.br/judge/pt/"
	"CodeForces												- https://codeforces.com/"
	"OverLeaf												- https://pt.overleaf.com/project"
	"Outlook												- https://outlook.live.com/"
	"OneDrive												- https://onedrive.live.com/"
	"Fluent C++												- https://www.fluentcpp.com/"
	"CP algorithms											- https://cp-algorithms.com/string/suffix-automaton.html"
)
touch ListaFavoChrome
for favorito in ${FAV[*]}; do
	echo $favorito >> ListaFavoChrome
done

## Criando Lista de Extensões do Chrome
EXT=(
	"Dark Reader 							- https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=pt-BR"
	"Evernote Clipper 						- https://evernote.com/intl/pt-br/features/webclipper"
	"Zenhub									- https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd?hl=pt-BR"
)
touch ListaExtChrome
for extensao in ${EXT[*]}; do
	echo $extensao >> ListaExtChrome
done

## Git
cd $HOME
mkdir UnB && cd UnB
git clone https://github.com/SergioAlmeidaCiprianoJr/Practice.git
git clone https://github.com/edsomjr/TEP.git
git clone https://github.com/xstpl/Livros-1
git clone https://github.com/SergioAlmeidaCiprianoJr/Optimization.jl.git

## Snap install
snap install code --classic
snap install sublime-text
snap install spotify

## Finalizando, atualizando e limpando
sudo apt update && sudo apt dist-upgrade -y
flatpak update
sudo apt autoclean
sudo apt autoremove -y
